//LOCALHOST
# Get all users
GET http://localhost:3000/users

### Get User by ID
GET http://localhost:3000/users/6a2267b10784060e5b16f579

### Create a new user
POST http://localhost:3000/users HHTTP/1.1
Content-Type: application/json

{
  "firstName": "Ashley",
  "lastName": "Weaver",
  "email": "Ashley.Weaver@gmail.com",
  "favoriteDestination": "Managua, Nicaragua",
  "hotel": "Holiday Inn",
  "transportation": "Car"
}

### PUT user
PUT http://localhost:3000/users/6a2267b10784060e5b16f579 HTTP/1.1
Content-Type: application/json

{
  "email": "victor.vega@gmail.com",
  "favoriteDestination": "Miami",
  "hotel": "Hilton",
  "transportation": "airplane",
  "firstName": "Victor",
  "lastName": "Vega"
}

### Delete user
DELETE http://localhost:3000/users/6a2267b10784060e5b16f579


